owner/urls.py
from django.urls import path
from owner.views import *

app_name = 'owner'
urlpatterns = [
    path('dashboard/', dashboard, name='dashboard_owner'),
    path('list-all-service/', list_all_service, name='list_all_service'),
    path('service-detail/<int:service_id>/', service_detail, name='service_detail'),
    path('add-user/', add_user, name='add_user'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.auth.views import LogoutView 
from .views import *
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('technician/', include('technician.urls')),
    path('staff/', include('staff.urls')),
    path('owner/', include('owner.urls')),
    path('logout/', logout_view, name='logout'),
    path('play-video/<str:filename>/', play_video, name='play_video'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from staff.views import *

app_name = 'staff'
urlpatterns = [
    path('dashboard/', dashboard, name='dashboard_staff'),
    path('service-approval-list/', service_approval_list, name='service_approval_list'),
    path('service-detail/<int:service_id>/', service_detail, name='service_detail'),
    path('generate-pdf/<int:car_service_id>/', generate_pdf, name='generate_pdf'),
]

owner/models.py
from django.db import models

# Create your models here.

owner/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from authentication.models import UserManage
from technician.models import CarService
from utility.util import check_is_completed, generateRandomString
from django.conf import settings
from technician.models import CarService, PartToService
from django.core.mail import send_mail

WEBURL = settings.CSRF_TRUSTED_ORIGINS[0]

@login_required
def dashboard(request):
    username = request.user.username
    context = {'username': username}
    return render(request, 'dashboard_owner.html', context=context)

@login_required
def list_all_service(request):
    context = dict()
    if request.method == 'POST':
        idToRestore = request.POST.get('restore')
        car_service = CarService.objects.get(pk=int(idToRestore))
        car_service.is_deleted = False
        car_service.save()

    if request.user.is_owner:
        car_services = CarService.objects.all()

        rendered_car_services = []
        for car_service in car_services:

            parts_to_service = car_service.part_to_service.all()
            status_now = None
            if check_is_completed(parts_to_service):
                status_now = "Aktif"
            else:
                status_now = "Belum diputuskan"
            if car_service.is_deleted:
                status_now = "Deleted"
            rendered_car_services.append((car_service, car_service.service_date.strftime('%Y-%m-%d'), status_now))
        context['car_services'] = rendered_car_services
        return render(request, 'list_all_service.html', context)
    else:
        return redirect('owner:dashboard_owner')
    
def service_detail(request, service_id):
    car_service = CarService.objects.get(pk=service_id)

    parts_to_service = car_service.part_to_service.all()
    status_complete_before_post = check_is_completed(parts_to_service)

    if request.method == 'POST':
        car_service_id = request.POST.get('car_service_id')
        part_to_service_id = request.POST.get('part_to_service_id')
        reason = request.POST.get('reason')
        action = request.POST.get('action')

        if action == 'approve':
            part_to_service = PartToService.objects.get(pk=part_to_service_id)
            part_to_service.is_approved = True
        elif action == 'reject':
            part_to_service = PartToService.objects.get(pk=part_to_service_id)
            part_to_service.is_rejected = True
        part_to_service.validated_by = request.user.username
        part_to_service.reason = reason
        part_to_service.save()

        car_service = CarService.objects.get(pk=car_service_id)
    
    parts_to_service = car_service.part_to_service.all()

    is_completed = check_is_completed(parts_to_service)

    if (not status_complete_before_post) and (is_completed):
        print(send_mail(
            f"Pesanan Service Mobil Baru ke-{service_id}",
            f"Haloo, Terdapat Pesanan Service Mobil yang telah diputuskan\n\nBerikut merupakan linknya: {WEBURL}staff/generate_pdf/{service_id}/\n\n",
            f"{settings.EMAIL_HOST_USER}",
            recipient_list=["Rickyprawiro@yahoo.com"],
            fail_silently=False,
        ))

    appended_parts = []
    for part_to_service in parts_to_service:
        try:
            appended_parts.append((part_to_service, str(part_to_service.car_video.url).split("/")[-1]))
        except:
            appended_parts.append((part_to_service, None))

    no_wa_temp = car_service.techinician_phone.strip()
    if no_wa_temp.startswith("0"):
        no_wa_temp = "62" + no_wa_temp[1:]
    whatsapp_link = f'https://api.whatsapp.com/send?phone={no_wa_temp}&text=Haloo%2C%20Terdapat%20Pesanan%20Service%20Mobil%20yang%20telah%20diputuskan%0A%0ABerikut%20merupakan%20linknya%3A%20{WEBURL}staff/generate_pdf/{service_id}%2F%0A%0A'
    
    context = {'car_service': car_service, 'parts_to_service_list':appended_parts, 'is_completed':is_completed, 'whatsapp_link':whatsapp_link}
    return render(request, 'service_detail_owner.html', context)

def add_user(request):
    context = dict()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        role = request.POST.get('role')

        try:
            if role == 'technician':
                user = UserManage.objects.create_user(username=username, password=password)
                user.is_technician = True
            elif role == 'staff_member':
                user = UserManage.objects.create_user(username=username, password=password)
                user.is_staff_member = True
            elif role == 'owner':
                user = UserManage.objects.create_superuser(username=username, email=f"{generateRandomString()}@gmail.com", password=password)
                user.is_owner = True

            user.save()

            context['message_flag'] = 'success'
            context['message'] = f'Sukses menyimpan user "{username}" sebagai {role}'
        except Exception as e:
            context['message_flag'] = 'danger'
            context['message'] = str(e)

    return render(request, 'add_user.html', context)

owner/templates/add_user.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Add User</title>
{% endblock meta %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<div class="content-container d-flex align-items-center justify-content-center mx-auto">
    <div class="container">
        <h2>Add User <strong>Hobi Mobil</strong></h2>
        {% if message %}
            <div class="alert alert-{{message_flag}}">
                {{ message }}
            </div>
        {% endif %}
        <form method="post" onsubmit="return validateForm()">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username" required>
            </div>
            <div class="form-group mb-3">
                <label for="password">Password:</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" required>
            </div>
            <label>Role:</label>
            <div class="form-check">
                <input type="radio" class="form-check-input" id="is_technician" name="role" value="technician" required>
                <label class="form-check-label" for="is_technician">Technician</label>
            </div>
            <div class="form-check">
                <input type="radio" class="form-check-input" id="is_staff_member" name="role" value="staff_member" required>
                <label class="form-check-label" for="is_staff_member">Staff Member</label>
            </div>
            <div class="form-check">
                <input type="radio" class="form-check-input" id="is_owner" name="role" value="owner" required>
                <label class="form-check-label" for="is_owner">Owner</label>
            </div>
            <button type="submit" class="mt-2 btn btn-primary btn-custom btn-block">Submit</button>
        </form>
    </div>
</div>

<script>
    function validateForm() {
        var password = document.getElementById("password").value;

        if (password.length < 8) {
            alert("Password must be at least 8 characters long");
            return false;
        }

        var hasLetter = /[a-zA-Z]/.test(password);
        var hasNumber = /\d/.test(password);

        if (!hasLetter || !hasNumber) {
            alert("Password must contain at least one letter and one number");
            return false;
        }

        // If all checks pass, the form is submitted
        return true;
    }
</script>
{% endblock content %}

owner/templates/dashboard_owner.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Dashboard Owner - CAR SERVICE</title>
{% endblock meta %}

{% block content %}
<div class="content-container d-flex align-items-center justify-content-center mx-auto ">
	<div class="container rounded mt-2 mb-2">
		<div class="row align-items-center">
			<div class="col-md-3 align-items-center">
				<div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5 border border-secondary mb-2" width="150px" alt="default profile picture" src="https://static.vecteezy.com/system/resources/thumbnails/002/534/006/small/social-media-chatting-online-blank-profile-picture-head-and-body-icon-people-standing-icon-grey-background-free-vector.jpg">
					<span class="font-weight-bold" id="full-name"></span>
					<span class="text-black-50" id="username1"></span>
					<span class="fw-light" id="contributor"></span>
				</div>
			</div>
			<div class="col-md-9">
				<div class="d-flex justify-content-between align-items-center">
					<h3><strong>Dashboard</strong></h3>
				</div>
				<div class="row mt-2">
					<div class="col-md-12">
                        <label class="labels">Username</label>
                        <input type="text" aria-labelledby="nama" class="form-control" placeholder="" value="{{ username }}" id="nama" disabled="true">
                    </div>
				</div>
				<div class="row mt-2">
					<div class="col-md-12">
                        <label class="labels">Status</label>
                        <input type="text" aria-labelledby="negara" class="form-control" placeholder="" value="Owner" id="negara-edit" disabled="true">
                    </div>
				</div>
				<div class="btn-toolbar mt-3 mx-3" role="toolbar" aria-label="Toolbar with button groups">
					<div class="btn-group me-2" role="group" aria-label="First group">
						<a href="{% url 'owner:list_all_service' %}" class="btn btn-primary btn-block">List All Service</a>
					</div>
					<div class="btn-group me-2" role="group" aria-label="Second group">
						<a href="/admin" class="btn btn-primary btn-block">Admin Django</a>
					</div>
					<div class="btn-group me-2" role="group" aria-label="Third group">
						<a href="{% url 'owner:add_user' %}" class="btn btn-primary btn-block">Add User</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

owner/templates/list_all_service.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2 class="mt-3 text-white">Service Approval List</h2>
    <div class="card mb-2 bg-light">
        <div class="row justify-content-center">
            <div class="col-md-3">
                <div class="form-group">
                    <label for="technicianName">Filter by Technician Name:</label>
                    <input type="text" id="technicianName" name="technicianName" class="form-control" oninput="filterTable()">
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="licenseNumber">Filter by License Plate:</label>
                    <input type="text" id="licenseNumber" name="licenseNumber" class="form-control" oninput="filterTable()">
                </div>
            </div>
            <div class="col-md-2 mr-3">
                <div class="form-group">
                    <label for="serviceDate">Filter by Service Date:</label>
                    <input type="date" id="serviceDate" name="serviceDate" class="form-control" oninput="filterTable()">
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <label for="columnSelect">Sort by Column:</label>
                    <select id="columnSelect" class="btn btn-secondary dropdown-toggle">
                        <option value="id">Id</option>
                        <option value="technician_name">Nama Teknisi</option>
                        <option value="license_plate">Plat Nomor</option>
                        <option value="brand">Brand Mobil</option>
                        <option value="service_date_formatted">Service Date</option>
                        <option value="status_now">Status</option>
                    </select>
                </div>
            </div>
            <div class="col-md-1">
                <div class="form-group">
                    <label for="orderSelect">Order</label>
                    <select id="orderSelect" class="btn btn-secondary dropdown-toggle">
                        <option value="asc">Asc</option>
                        <option value="desc">Desc</option>
                    </select>
                </div>
            </div>
            <div class="col-md-1">
                <div class="pagination mb-2">
                    <button onclick="prevPage()" class="btn btn-primary">Prev</button>
                    <span id="currentPage" class="btn btn-outline-primary" disabled aria-disabled="true">1</span>
                    <button onclick="nextPage()" class="btn btn-primary">Next</button>
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table" id="serviceTable">
            <thead>
                <tr>
                    <th>ID Car Service</th>
                    <th>Nama Teknisi</th>
                    <th>Plat Nomor</th>
                    <th>Merek/Tipe</th>
                    <th>Part yang Service</th>
                    <th>Foto Part</th>
                    <th>Tanggal Servis</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="tableBody">
            </tbody>
        </table>
    </div>
</div>

<script>
    var tableData = [];
    var currentPage = 1;
    var itemsPerPage = 10;

    document.addEventListener('DOMContentLoaded', function () {
        var columnSelect = document.getElementById("columnSelect");
        var orderSelect = document.getElementById("orderSelect");

        columnSelect.value = "service_date_formatted";
        orderSelect.value = "desc";

        columnSelect.addEventListener("change", filterTable);
        orderSelect.addEventListener("change", filterTable);

        {% for car_service, service_date_formatted, status_now in car_services %}
        tableData.push({
            id: {{ car_service.id }},
            user: '{{ car_service.user.username }}',
            technician_name: '{{ car_service.techinician_name }}',
            license_plate: '{{ car_service.license_plate }}',
            brand: '{{ car_service.brand }}',
            parts_to_service: [
                {% for part_to_service in car_service.part_to_service.all %}
                    '{{ part_to_service.parts_to_service }}',
                {% endfor %}
            ],
            car_photos: [
                {% for part_to_service in car_service.part_to_service.all %}
                    '{{ part_to_service.car_photo.url }}',
                {% endfor %}
            ],
            service_date: '{{ car_service.service_date }}',
            service_detail_url: '{% url 'owner:service_detail' car_service.id %}',
            status_now: '{{ status_now }}',
            service_date_formatted: '{{ service_date_formatted }}'
        });
        {% endfor %}

        updateCurrentPage();
        filterTable();
    });

    function populateTable(tableData) {
        var tableBody = document.getElementById("tableBody");
        tableBody.innerHTML = "";
    
        // Iterate through the array and create table rows
        tableData.forEach(function (car_service) {
            var row = document.createElement("tr");
            row.id = "data_table";
            row.innerHTML = `
                <td>${car_service.id}</td>
                <td>${car_service.technician_name}</td>
                <td>${car_service.license_plate}</td>
                <td>${car_service.brand}</td>
                <td>${car_service.parts_to_service.join("<br>") || 'No parts to service'}</td>
                <td>${car_service.car_photos.slice(0,1).map(photo => `<img src="${photo}" alt="Part Photo" width="60"><br>`).join('') || 'No part photos'}</td>
                <td>${car_service.service_date}</td>
                <td style="color: ${car_service.status_now === 'Belum diputuskan' ? 'red' : 'inherit'}; font-weight: ${car_service.status_now === 'Belum diputuskan' ? 'bold' : 'normal'}">
                    ${car_service.status_now}
                </td>
                <td>
                    <a href="${car_service.service_detail_url}" class="btn btn-info">Detail</a>
                    ${car_service.status_now === 'Deleted' ? `
                        <form method="post" onsubmit="return confirmRestore()">
                            {% csrf_token %}
                            <button type="submit" name="restore" value="${car_service.id}" class="btn btn-success">Restore</button>
                        </form>` : ''}
                </td>
            `;
            tableBody.appendChild(row);
        });
    }

    function confirmRestore() {
        return confirm("Are you sure you want to restore this entry?");
    }

    function filterTable() {
        var technicianInput = document.getElementById("technicianName");
        var licenseNumberInput = document.getElementById("licenseNumber");
        var serviceDateInput = document.getElementById("serviceDate");
        var technicianFilter = technicianInput.value.toUpperCase();
        var licenseNumberFilter = licenseNumberInput.value.toUpperCase();
        var serviceDateFilter = serviceDateInput.value;
    
        // Convert serviceDateFilter to the desired format (if needed)
        if (serviceDateFilter) {
            serviceDateFilter = formatDate(serviceDateFilter);
        }
    
        var filteredData = tableData.filter(function (item) {
            var isTechnicianMatch = (item.technician_name.toUpperCase().indexOf(technicianFilter) > -1) || !technicianFilter;
            var isLicenseNumberMatch = (item.license_plate.toUpperCase().indexOf(licenseNumberFilter) > -1) || !licenseNumberFilter;
            var isServiceDateMatch = (!serviceDateFilter || item.service_date.indexOf(serviceDateFilter) > -1);
    
            return isTechnicianMatch && isLicenseNumberMatch && isServiceDateMatch;
        });

        var selectedColumn = document.getElementById("columnSelect").value;
        var selectedOrder = document.getElementById("orderSelect").value;

        // Sort the filtered data based on the selected column and order
        if (selectedOrder === "asc") {
            filteredData.sort((a, b) => (a[selectedColumn] > b[selectedColumn]) ? 1 : -1);
        } else {
            filteredData.sort((a, b) => (a[selectedColumn] < b[selectedColumn]) ? 1 : -1);
        }
    
        // Update your table or perform any necessary actions with the filtered data
        // Adjust the range of items to display based on the current page
        var startIndex = (currentPage - 1) * itemsPerPage;
        var endIndex = startIndex + itemsPerPage;

        // Populate the table with the filtered and paginated data
        populateTable(filteredData.slice(startIndex, endIndex));
    }

    function updateCurrentPage() {
        document.getElementById("currentPage").innerText = currentPage;
    }

    function prevPage() {
        if (currentPage > 1) {
            currentPage--;
            updateCurrentPage();
            filterTable();
        }
    }

    function nextPage() {
        var maxPage = Math.ceil(tableData.length / itemsPerPage);
        if (currentPage < maxPage) {
            currentPage++;
            updateCurrentPage();
            filterTable();
        }
    }

    function formatDate(inputDate) {
        // Create a Date object from the input date string
        var date = new Date(inputDate);

        // Get the month name abbreviation
        var monthNames = [
            "Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.",
            "Jul.", "Aug.", "Sep.", "Oct.", "Nov.", "Dec."
        ];
        var monthAbbreviation = monthNames[date.getMonth()];

        // Get the day and year components
        var day = date.getDate();
        var year = date.getFullYear();

        // Create the formatted date string
        var formattedDate = monthAbbreviation + ' ' + day + ', ' + year;

        return formattedDate;
    }
</script>

{% endblock content %}

owner/templates/service_detail_owner.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2 class="mt-3 text-white" style="margin-top: 10px;">Service Detail</h2>
    <table class="table">
        <tr>
            <th>ID Car Service</th>
            <td>{{ car_service.id }}</td>
        </tr>
        <tr>
            <th>Username Pendaftar</th>
            <td>{{ car_service.user.username }}</td>
        </tr>
        <tr>
            <th>Plat Nomor</th>
            <td>{{ car_service.license_plate }}</td>
        </tr>
        <tr>
            <th>Merek / Tipe Mobil</th>
            <td>{{ car_service.brand }}</td>
        </tr>
        <tr>
            <th>Tanggal Servis</th>
            <td>{{ car_service.service_date }}</td>
        </tr>
        <tr>
            <th>Nama Tukang Servis</th>
            <td>{{ car_service.techinician_name }}</td>
        </tr>
        <tr>
            <th>Nomor Telepon Tukang Servis</th>
            <td>{{ car_service.techinician_phone }}</td>
        </tr>
        <tr>
            <th>Daftar Part Servis</th>
            <td>
                {% for part_to_service, videoname in parts_to_service_list %}
                    <p>
                        <strong>Nama Servis Part {{ forloop.counter }}:</strong><br>
                        {{ part_to_service.parts_to_service }}
                    </p>
                    <p>
                        <strong>Media Servis Part {{ forloop.counter }}:</strong><br>
                        <img src="{{ part_to_service.car_photo.url }}" alt="{{ part_to_service.parts_to_service }} Photo" width="200"><br>
                        <a href="{{ part_to_service.car_photo.url }}" target="_blank" class="btn btn-info">View Photo</a>
                        {% if part_to_service.car_video %}
                            <a href="{% url 'play_video' videoname %}" target="_blank" class="btn btn-info">View Video</a>
                        {% endif %}
                    </p>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="car_service_id" value="{{ car_service.id }}">
                        <input type="hidden" name="part_to_service_id" value="{{ part_to_service.id }}">
                        {% if part_to_service.is_approved %}
                            &#9989 Disetujui oleh {{ part_to_service.validated_by }}<br>
                            <strong>Alasan:</strong> {{ part_to_service.reason }}
                        {% elif part_to_service.is_rejected %}
                            &#10060 Ditolak oleh {{ part_to_service.validated_by }};<br>
                            <strong>Alasan:</strong> {{ part_to_service.reason }}
                        {% else %}
                            <button type="submit" name="action" value="approve" class="btn btn-success mb-3">Accept</button>
                            <button type="submit" name="action" value="reject" class="btn btn-danger mb-3">Reject</button><br>
                            <textarea name="reason" placeholder="Alasan" class="form-control col-12 col-md-6" required></textarea>
                        {% endif %}
                    </form>
                    <br>
                    <br>
                {% endfor %}
            </td>
        </tr>
    </table>
    <a href="{% url 'owner:list_all_service' %}" class="btn btn-primary">Kembali ke Approval List</a>

    {% if is_completed %}
        <a href="{% url 'staff:generate_pdf' car_service.id %}" class="btn btn-danger">Buat PDF</a>
        <a href="{{ whatsapp_link }}" class="btn btn-success" target="_blank">Kirim Pesan WhatsApp</a>
    {% endif %}
    <p></p>
</div>
{% endblock content %}