owner/urls.py
from django.urls import path
from owner.views import *

app_name = 'owner'
urlpatterns = [
    path('dashboard/', dashboard, name='dashboard_owner'),
    path('list-all-service/', list_all_service, name='list_all_service'),
    path('service-detail/<int:service_id>/', service_detail, name='service_detail'),
    path('add-user/', add_user, name='add_user'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.auth.views import LogoutView 
from .views import *
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('technician/', include('technician.urls')),
    path('staff/', include('staff.urls')),
    path('owner/', include('owner.urls')),
    path('logout/', logout_view, name='logout'),
    path('play-video/<str:filename>/', play_video, name='play_video'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

technician/urls.py
from django.urls import path
from technician.views import *

app_name = 'technician'
urlpatterns = [
    path('dashboard/', dashboard, name='dashboard_technician'),
    path('create-service-form/',create_service_form, name='create_service_form'),
    path('list-for-edit/',list_for_edit, name='list_for_edit'),
    path('edit-service/<int:service_id>/', edit_service, name='edit_service'),
    path('history-service/', history_service, name='history_service'),
]

technician/models.py
from django.db import models
from authentication.models import UserManage

class CarService(models.Model):
    user = models.ForeignKey(UserManage, on_delete=models.CASCADE, related_name='car_services')
    license_plate = models.CharField(max_length=20)
    brand = models.CharField(max_length=50)
    service_date = models.DateField(default=None)
    techinician_name = models.CharField(max_length=100, default="None")  # Tambahkan field Nama Staff Service
    techinician_phone = models.CharField(max_length=15, default="None")  # Tambahkan field Nomor HP Tukang Service
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username}'s Car Service Information"
    
class PartToService(models.Model):
    car_service = models.ForeignKey(CarService, on_delete=models.CASCADE, related_name='part_to_service')

    id_order = models.IntegerField(default=1)
    parts_to_service = models.TextField(default=None)
    car_photo = models.ImageField(upload_to='car_photos/', blank=True, null=True)
    car_video = models.FileField(upload_to='videos/', null=True, verbose_name="")
    created_at = models.DateTimeField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    validated_by = models.CharField(max_length=30)
    reason = models.TextField(default="")

    def __str__(self):
        return f"PartToService for {self.car_service.user.username}'s Car Service text: {self.parts_to_service}"

technician/views.py
import datetime
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from utility.util import check_is_completed
from .models import CarService, PartToService
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from django.shortcuts import get_object_or_404

@login_required
def dashboard(request):
    username = request.user.username
    context = {'username': username}
    return render(request, 'dashboard_technician.html', context=context)

@login_required
def create_service_form(request):
    if request.method == 'POST':
        num_parts = int(request.POST.get('num_parts', 1))  # Ambil jumlah parts yang ingin dibuat, defaultnya 1

        license_plate = request.POST.get('license_plate')
        brand = request.POST.get('brand')
        techinician_name = request.POST.get('staff_service_name')
        techinician_phone = request.POST.get('phone_number')
        service_date = request.POST.get('tanggal')

        print(f"service_date: {service_date}")
        car_service = CarService.objects.create(
            user=request.user,
            license_plate=license_plate,
            brand=brand,
            service_date=datetime.datetime.strptime(service_date, '%Y-%m-%d'),
            techinician_name=techinician_name,
            techinician_phone=techinician_phone,
        )

        # Simpan PartToService berdasarkan jumlah yang diinginkan
        for i in range(num_parts):
            part_to_service_text = request.POST.get(f'part_to_service_{i}')
            car_photo = request.FILES.get(f'car_photo_{i}')
            car_video = request.FILES.get(f'car_video_{i}')

            if part_to_service_text:
                if not car_video:
                    part_to_service = PartToService(
                        id_order = i,
                        car_service=car_service,
                        parts_to_service=part_to_service_text,
                        car_photo=car_photo
                    )
                else:
                    part_to_service = PartToService(
                        id_order = i,
                        car_service=car_service,
                        parts_to_service=part_to_service_text,
                        car_photo=car_photo,
                        car_video=car_video
                    )
                part_to_service.save()

        return render(request, 'create_service_form.html', {'status': 'success'})
    else:
        return render(request, 'create_service_form.html')

@login_required
def list_for_edit(request):
    context = dict()
    if request.user.is_technician:
        selected = []
        car_services = CarService.objects.filter(user=request.user)

        for car_service in car_services:
            if car_service.is_deleted:
                continue
            parts_to_service = car_service.part_to_service.all()
            if not check_is_completed(parts_to_service):
                selected.append(car_service)

        context = {'car_services': selected}
        return render(request, 'list_for_edit.html', context)
    else:
        return redirect('technician:dashboard_technician')
    
@login_required
def history_service(request):
    context = dict()
    if request.user.is_technician:
        selected = []
        car_services = CarService.objects.filter(user=request.user)

        for car_service in car_services:
            if car_service.is_deleted:
                continue
            parts_to_service = car_service.part_to_service.all()
            if check_is_completed(parts_to_service):
                selected.append((car_service, "Aktif"))
            else:
                selected.append((car_service, "Belum diputuskan"))

        context['car_services'] = selected
        return render(request, 'history_service.html', context)
    else:
        return redirect('technician:dashboard_technician')
    
@login_required
def edit_service(request, service_id):
    context = dict()
    if request.user.is_technician and request.method == 'POST':
        car_service = CarService.objects.get(pk=service_id)

        num_parts = int(request.POST.get('num_parts', 1))

        license_plate = request.POST.get('license_plate')
        brand = request.POST.get('brand')
        techinician_name = request.POST.get('staff_service_name')
        techinician_phone = request.POST.get('phone_number')
        service_date = request.POST.get('tanggal')

        if car_service.license_plate != license_plate:
            car_service.license_plate = license_plate
        if car_service.brand != brand:
            car_service.brand = brand
        if car_service.techinician_name != techinician_name:
            car_service.techinician_name = techinician_name
        if car_service.techinician_phone != techinician_phone:
            car_service.techinician_phone = techinician_phone
        if car_service.service_date != service_date:
            car_service.service_date = service_date
        car_service.save()

        for i in range(num_parts):
            part_to_service_text = request.POST.get(f'part_to_service_{i}')
            car_photo = request.FILES.get(f'car_photo_{i}')
            car_video = request.FILES.get(f'car_video_{i}')
            try:
                part_to_service = PartToService.objects.get(car_service=car_service, id_order=i)
                if part_to_service.parts_to_service != part_to_service_text:
                    part_to_service.parts_to_service = part_to_service_text
                if car_photo:
                    part_to_service.car_photo = car_photo
                if car_video:
                    part_to_service.car_video = car_video
                part_to_service.save()
            except:
                part_to_service = PartToService(
                    id_order = i,
                    car_service=car_service,
                    parts_to_service=part_to_service_text,
                    car_photo=car_photo if car_photo else None,
                    car_video=car_video if car_video else None,
                )
                part_to_service.save()

        for part_service in car_service.part_to_service.all():
            if part_service.id_order > num_parts-1:
                part_service.delete()

        context['status'] = 'success'

    if request.user.is_technician:
        car_service = CarService.objects.get(pk=service_id)
        parts_to_service = car_service.part_to_service.all()
        context['car_service'] = car_service
        context['converted_date'] = car_service.service_date.strftime('%Y-%m-%d')
        context['parts_to_service'] = parts_to_service
        text_name = []
        enum_parts = []
        for i, part in enumerate(parts_to_service):
            text_name.append(part.parts_to_service)
            enum_parts.append((i, i+1, part))
        context['text_name'] = text_name
        context['enum_parts'] = enum_parts
        context['len_parts_to_service'] = len(parts_to_service)
        return render(request, 'edit_service.html', context)
    else:
        return redirect('technician:dashboard_technician')

@login_required
def test_play_video(request):
    return render(request, 'test_play_video.html')

technician/templates/create_service_form.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Buat Service Form - CAR SERVICE</title>
{% endblock meta %}

{% block content %}
<div class="content-container d-flex align-items-center justify-content-center mx-auto">
    <div class="container">
        <h2>Buat Service Form</h2>
        
        {% if status == 'success' %}
            <div class="alert alert-success">
                Form Isian Telah Sukses Terkirim
            </div>
        {% endif %}
        
        <a href="{% url 'technician:dashboard_technician' %}" class="btn btn-primary mb-3">Back to Dashboard</a>
        
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div style="display: flex;" id="flex-container">
            </div>
            <button type="submit" class="btn btn-primary">Kirim</button>
        </form>        
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        chooseColumnOrRow();

        const partsContainer = document.getElementById('parts-container');
        const numPartsInput = document.getElementById('num_parts');
        const tanggalInput = document.getElementById('tanggal');  // Tambahkan ini
        
        // Set nilai default untuk input Tanggal
        const today = new Date();
        const year = today.getFullYear();
        const month = String(today.getMonth() + 1).padStart(2, '0');
        const day = String(today.getDate()).padStart(2, '0');
        const todayString = `${year}-${month}-${day}`;
        tanggalInput.value = todayString;
    
        function addInputFields(numParts) {
            partsContainer.innerHTML = '';
    
            for (let i = 0; i < numParts; i++) {
                partsContainer.innerHTML += `
                    <div class="form-group">
                        <label for="part_to_service_${i}">Part ke-${i + 1}</label>
                        <input type="text" class="form-control" id="part_to_service_${i}" name="part_to_service_${i}" placeholder="Masukan Nama Part" required>
                    </div>
                    <div class="form-group">
                        <label for="car_photo_${i}">Foto Part ke-${i + 1}</label>
                        <input type="file" class="form-control-file" id="car_photo_${i}" name="car_photo_${i}" required accept="image/*">
                    </div>
                    <div class="form-group">
                        <label for="car_video_${i}">[Tidak Wajib] Video Part ke-${i + 1}</label>
                        <input type="file" class="form-control-file" id="car_video_${i}" name="car_video_${i}" accept="video/*">
                    </div>
                `;
            }
        }
    
        numPartsInput.addEventListener('input', function () {
            const numParts = parseInt(numPartsInput.value);
    
            if (isNaN(numParts) || numParts < 1) {
                numParts = 1;
                numPartsInput.value = numParts;
            }

            addInputFields(numParts);
        });
    
        addInputFields(parseInt(numPartsInput.value));
        

    });

    function handleResize() {
        chooseColumnOrRow();
    }

    function chooseColumnOrRow() {
        const flexContainer = document.getElementById('flex-container');
        if (window.innerWidth >= window.innerHeight) {
            flexContainer.innerHTML = `<!-- Kolom Kiri -->
                <div style="flex: 1; padding: 0 10px;">
                    <div class="form-group">
                        <label for="staff_service_name">Nama Tukang Servis</label>
                        <input type="text" class="form-control" id="staff_service_name" name="staff_service_name" placeholder="Masukan Nama Tukang Servis" required value="{{ user_full_name }}">
                    </div>
                    <div class="form-group">
                        <label for="license_plate">Plat Nomor</label>
                        <input type="text" class="form-control" id="license_plate" name="license_plate" placeholder="Masukan Plat Nomor" required>
                    </div>
                    <div class="form-group">
                        <label for="brand">Merek/Tipe</label>
                        <input type="text" class="form-control" id="brand" name="brand" placeholder="Masukan Merek Mobil" required>
                    </div>
                    <div class="form-group">
                        <label for="phone_number">No Telepon Tukang Servis</label>
                        <input type="number" class="form-control" id="phone_number" name="phone_number" placeholder="Masukan No Telp Tukang" required value="{{ user_phone_number }}">
                    </div>
                    <div class="form-group">
                        <label for="tanggal">Tanggal Service</label>
                        <input type="date" class="form-control" id="tanggal" name="tanggal" required>
                    </div>
                </div>
                <!-- Kolom Kanan -->
                <div style="flex: 1; padding: 0 10px;">
                    <div class="form-group">
                        <label for="num_parts">Jumlah of Part yang di Servis</label>
                        <input type="number" class="form-control" id="num_parts" name="num_parts" placeholder="Masukan Jumlah Part" required value="1">
                    </div>
                    <div id="parts-container"></div>
                </div>`
        } else {
            flexContainer.innerHTML += `<!-- Kolom Kiri -->
                <div style="flex: 1; padding: 0 10px;">
                    <div class="form-group">
                        <label for="staff_service_name">Nama Tukang Servis</label>
                        <input type="text" class="form-control" id="staff_service_name" name="staff_service_name" placeholder="Masukan Nama Tukang Servis" required value="{{ user_full_name }}">
                    </div>
                    <div class="form-group">
                        <label for="license_plate">Plat Nomor</label>
                        <input type="text" class="form-control" id="license_plate" name="license_plate" placeholder="Masukan Plat Nomor" required>
                    </div>
                    <div class="form-group">
                        <label for="brand">Merek/Tipe</label>
                        <input type="text" class="form-control" id="brand" name="brand" placeholder="Masukan Merek Mobil" required>
                    </div>
                    <div class="form-group">
                        <label for="phone_number">No Telepon Tukang Servis</label>
                        <input type="number" class="form-control" id="phone_number" name="phone_number" placeholder="Masukan No Telp Tukang" required value="{{ user_phone_number }}">
                    </div>
                    <div class="form-group">
                        <label for="tanggal">Tanggal Service</label>
                        <input type="date" class="form-control" id="tanggal" name="tanggal" required>
                    </div>
                    <div class="form-group">
                        <label for="num_parts">Jumlah of Part yang di Servis</label>
                        <input type="number" class="form-control" id="num_parts" name="num_parts" placeholder="Masukan Jumlah Part" required value="1">
                    </div>
                    <div id="parts-container"></div>
                </div>`
        }
    }
</script>
    
{% endblock content %}

technician/templates/dashboard_technician.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Dashboard Technician - CAR SERVICE</title>
{% endblock meta %}

{% block content %}
<div class="content-container d-flex align-items-center justify-content-center mx-auto">
	<div class="container rounded mt-2 mb-2">
		<div class="row align-items-center">
			<div class="col-md-3 align-items-center">
				<div class="d-flex flex-column align-items-center text-center p-3 py-5">
					<img class="rounded-circle mt-5 border border-secondary mb-2" width="150px" alt="default profile picture" src="https://static.vecteezy.com/system/resources/thumbnails/002/534/006/small/social-media-chatting-online-blank-profile-picture-head-and-body-icon-people-standing-icon-grey-background-free-vector.jpg">
					<span class="font-weight-bold" id="full-name"></span>
					<span class="text-black-50" id="username1"></span>
					<span class="fw-light" id="contributor"></span>
				</div>
			</div>
			<div class="col-md-9">
				<div class="d-flex justify-content-between align-items-center">
					<h3><strong>Dashboard</strong></h3>
				</div>
				<div class="row mt-2">
					<div class="col-md-12">
						<label class="labels">Username</label>
						<input type="text" aria-labelledby="nama" class="form-control" placeholder="" value="{{ username }}" id="nama" disabled="true">
					</div>
				</div>
				<div class="row mt-2">
					<div class="col-md-12">
						<label class="labels">Status</label>
						<input type="text" aria-labelledby="negara" class="form-control" placeholder="" value="Technician" id="negara-edit" disabled="true">
					</div>
				</div>
				<div class="btn-toolbar mt-3 mx-3" role="toolbar" aria-label="Toolbar with button groups">
					<div class="btn-group me-2" role="group" aria-label="First group">
						<a href="{% url 'technician:create_service_form' %}" class="btn btn-primary">Buat Form Service</a>
					</div>
					<div class="btn-group me-2" role="group" aria-label="Second group">
						<a href="{% url 'technician:list_for_edit' %}" class="btn btn-primary btn-block">Edit Form</a>
					</div>
					<div class="btn-group me-2" role="group" aria-label="Second group">
						<a href="{% url 'technician:history_service' %}" class="btn btn-primary btn-block">Riwayat Form</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

technician/templates/edit_service.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Edit Service Form - CAR SERVICE</title>
{% endblock meta %}

{% block content %}
<div class="content-container d-flex align-items-center justify-content-center mx-auto">
    <div class="container">
        <h2>Edit Service Form</h2>
        
        {% if status == 'success' %}
            <div class="alert alert-success">
                Form Isian Telah Sukses Terubah
            </div>
        {% endif %}
        
        <a href="{% url 'technician:list_for_edit' %}" class="btn btn-danger mb-3">Cancel</a>
        
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div style="display: flex;" id="flex-container">
            </div>
            <button type="submit" class="btn btn-primary">Kirim</button>
        </form>        
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        chooseColumnOrRow();

        const partsContainer = document.getElementById('parts-container');
        const numPartsInput = document.getElementById('num_parts');
        const tanggalInput = document.getElementById('tanggal');  // Tambahkan ini
        
        // Set nilai default untuk input Tanggal
        const today = new Date();
        const year = today.getFullYear();
        const month = String(today.getMonth() + 1).padStart(2, '0');
        const day = String(today.getDate()).padStart(2, '0');
        const todayString = `${year}-${month}-${day}`;
        // tanggalInput.value = todayString;
        
        const arrAwal = {{ text_name|safe }};
        console.log(arrAwal);

        function addInputFields(numParts) {
            partsContainer.innerHTML = '';
    
            for (let i = 0; i < numParts; i++) {
                if (i < arrAwal.length) {
                    partsContainer.innerHTML += `
                    <div class="form-group">
                        <label for="part_to_service_${i}">Part ke-${i + 1}</label>
                        <input type="text" value="${arrAwal[i]}" class="form-control" id="part_to_service_${i}" name="part_to_service_${i}" placeholder="Enter Part to Service">
                    </div>
                    <div class="form-group">
                        <label for="car_photo_${i}">Ganti Foto Part ke-${i + 1}</label>
                        <input type="file" class="form-control-file" id="car_photo_${i}" name="car_photo_${i}" accept="image/*">
                    </div>
                    <div class="form-group">
                        <label for="car_video_${i}">[Tidak Wajib] Video Part ke-${i + 1}</label>
                        <input type="file" class="form-control-file" id="car_video_${i}" name="car_video_${i}" accept="video/*">
                    </div>
                `;
                } else {
                    partsContainer.innerHTML += `
                    <div class="form-group">
                        <label for="part_to_service_${i}">Part ke-${i + 1}</label>
                        <input type="text" class="form-control" id="part_to_service_${i}" name="part_to_service_${i}" placeholder="Enter Part to Service">
                    </div>
                    <div class="form-group">
                        <label for="car_photo_${i}">Tambahkan Foto Part ke-${i + 1}</label>
                        <input type="file" class="form-control-file" id="car_photo_${i}" name="car_photo_${i}" required accept="image/*">
                    </div>
                    <div class="form-group">
                        <label for="car_video_${i}">[Tidak Wajib] Video Part ke-${i + 1}</label>
                        <input type="file" class="form-control-file" id="car_video_${i}" name="car_video_${i}" accept="video/*">
                    </div>
                `;
                }
            

            }
        }
    
        numPartsInput.addEventListener('change', function () {
            const numParts = parseInt(numPartsInput.value);
    
            if (isNaN(numParts) || numParts < 1) {
                numParts = 1;
                numPartsInput.value = numParts;
            }

            addInputFields(numParts);
        });
    
        addInputFields(parseInt(numPartsInput.value));
        

    });

    function chooseColumnOrRow() {
        const flexContainer = document.getElementById('flex-container');
        if (window.innerWidth >= window.innerHeight) {
            flexContainer.innerHTML = `<!-- Kolom Kiri -->
                <div style="flex: 1; padding: 0 10px;">
                    <div class="form-group">
                        <label for="staff_service_name">Nama Tukang Servis</label>
                        <input type="text" value="{{ car_service.techinician_name }}" class="form-control" id="staff_service_name" name="staff_service_name" required>
                    </div>
                    <div class="form-group">
                        <label for="license_plate">Plat Nomor</label>
                        <input type="text" value="{{ car_service.license_plate }}" class="form-control" id="license_plate" name="license_plate" placeholder="Enter License Plate" required>
                    </div>
                    <div class="form-group">
                        <label for="brand">Merek/Tipe</label>
                        <input type="text" value="{{ car_service.brand }}" class="form-control" id="brand" name="brand" placeholder="Enter Car Brand" required>
                    </div>
                    <div class="form-group">
                        <label for="phone_number">No Telepon Tukang Servis</label>
                        <input type="number" value="{{ car_service.techinician_phone }}" class="form-control" id="phone_number" name="phone_number" required value="{{ user_phone_number }}">
                    </div>
                    <div class="form-group">
                        <label for="tanggal">Tanggal Service</label>
                        <input type="date" value="{{ converted_date }}" class="form-control" id="tanggal" name="tanggal" required>
                    </div>
                </div>
                <!-- Kolom Kanan -->
                <div style="flex: 1; padding: 0 10px;">
                    <div class="form-group">
                        <label for="num_parts">Jumlah of Part yang di Servis</label>
                        <input type="number" value="{{ len_parts_to_service }}" class="form-control" id="num_parts" name="num_parts" required value="1">
                    </div>
                    <div id="parts-container">
                    </div>
                </div>`
        } else {
            flexContainer.innerHTML += `<!-- Kolom Kiri -->
                <div style="flex: 1; padding: 0 10px;">
                    <div class="form-group">
                        <label for="staff_service_name">Nama Tukang Servis</label>
                        <input type="text" value="{{ car_service.techinician_name }}" class="form-control" id="staff_service_name" name="staff_service_name" required>
                    </div>
                    <div class="form-group">
                        <label for="license_plate">Plat Nomor</label>
                        <input type="text" value="{{ car_service.license_plate }}" class="form-control" id="license_plate" name="license_plate" placeholder="Enter License Plate" required>
                    </div>
                    <div class="form-group">
                        <label for="brand">Merek/Tipe</label>
                        <input type="text" value="{{ car_service.brand }}" class="form-control" id="brand" name="brand" placeholder="Enter Car Brand" required>
                    </div>
                    <div class="form-group">
                        <label for="phone_number">No Telepon Tukang Servis</label>
                        <input type="number" value="{{ car_service.techinician_phone }}" class="form-control" id="phone_number" name="phone_number" required value="{{ user_phone_number }}">
                    </div>
                    <div class="form-group">
                        <label for="tanggal">Tanggal Service</label>
                        <input type="date" value="{{ converted_date }}" class="form-control" id="tanggal" name="tanggal" required>
                    </div>
                    <div class="form-group">
                        <label for="num_parts">Jumlah of Part yang di Servis</label>
                        <input type="number" value="{{ len_parts_to_service }}" class="form-control" id="num_parts" name="num_parts" required value="1">
                    </div>
                    <div id="parts-container">
                    </div>
                </div>`
        }
    }
</script>
    
{% endblock content %}

technician/templates/list_for_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2 class="mt-3 text-white">Pilih untuk mengedit</h2>
    <a href="{% url 'technician:dashboard_technician' %}" class="btn btn-primary mb-3">Back to Dashboard</a>
    <div class="card-deck">
        {% for car_service in car_services %}
        <div class="card mb-4">
            <div class="card-body">
                <h5 class="card-title"><strong>ID Car Service:</strong> {{ car_service.id }}</h5>
                <p class="card-text"><strong>Nama Teknisi:</strong> {{ car_service.techinician_name }}</p>
                <p class="card-text"><strong>Plat Nomor:</strong> {{ car_service.license_plate }}</p>
                <p class="card-text"><strong>Merek/Tipe:</strong> {{ car_service.brand }}</p>
                <p class="card-text"><strong>Part yang Service:</strong></p>
                <ul class="list-unstyled">
                    {% for part_to_service in car_service.part_to_service.all %}
                        <li>• {{ part_to_service.parts_to_service }}</li>
                    {% empty %}
                        <li>No parts to service</li>
                    {% endfor %}
                </ul>
                <p class="card-text"><strong>Foto Part:</strong></p>
                <div>
                    {% for part_to_service in car_service.part_to_service.all %}
                        <img src="{{ part_to_service.car_photo.url }}" alt="{{ part_to_service.parts_to_service }} Photo" width="80" class="mr-2 mb-2">
                    {% empty %}
                        <p>No part photos</p>
                    {% endfor %}
                </div>
                <p class="card-text"><strong>Tanggal Servis:</strong> {{ car_service.service_date }}</p>
                <p class="card-text"><strong>Action:</strong> <a href="{% url 'technician:edit_service' car_service.id %}" class="btn btn-info">Edit</a></p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}